<?php
/*
===================================================================================================
WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

To make it easy to update your theme, you should not edit this file. Instead, you should create a
Child Theme first. This will ensure your template changes are not lost when updating the theme.

You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

You have been warned! :)
===================================================================================================
*/

// Current version of the theme
define( 'CHURCHTHEMES_CURRENT_VERSION', '1.3.3' );

// Theme options
define( 'CHURCHTHEMES_OPTIONS_MAIN_COLOR', '#f08d24' );
define( 'CHURCHTHEMES_OPTIONS_LOGO_WIDTH', 209 );
define( 'CHURCHTHEMES_OPTIONS_LOGO_HEIGHT', 56 );
define( 'CHURCHTHEMES_OPTIONS_LOGO_TOP_MARGIN', 50 );

// Custom background
define( 'CHURCHTHEMES_DEFAULT_BACKGROUND_IMAGE',  WP_THEME_DIR . '/images/bg_body.jpg'  );
define( 'CHURCHTHEMES_DEFAULT_BACKGROUND_COLOR', '101519' );

// Update script
define( 'CHURCHTHEMES_UPDATE_API_URL', 'http://churchthemes.net/updates/urbancity/' );

// PressTrends
define( 'CHURCHTHEMES_PRESSTRENDS_API_KEY', '6wtwv56il5mirnyk1gaiox0swbp3ut612rof' );
define( 'CHURCHTHEMES_PRESSTRENDS_THEME_AUTH', 'p0ezn81tdbtunr15lx89zrukrnzvg8jvh' );
