<?php
/*
===================================================================================================
WARNING! DO NOT EDIT THIS FILE OR ANY TEMPLATE FILES IN THIS THEME!

To make it easy to update your theme, you should not edit this file. Instead, you should create a
Child Theme first. This will ensure your template changes are not lost when updating the theme.

You can learn more about creating Child Themes here: http://codex.wordpress.org/Child_Themes

You have been warned! :)
===================================================================================================
*/
?>
<?php
$slide_settings = get_option('ct_slide_settings');
$visibility = isset( $slide_settings['visibility'] ) ? $slide_settings['visibility'] : null;
?>
<!DOCTYPE html>
<html <?php language_attributes() ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ) ?>" />
<title><?php wp_title( '|', true, 'right' ); bloginfo( 'name' ) ?></title>
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ) ?>" />
<?php wp_head() ?>
</head>
<body <?php body_class( 'no-js' ) ?>>
<div id="wrapper">
	<div id="wrapper2">
		<div id="header" class="container_12 grid-container">
			<div class="grid_3 grid-25 mobile-grid-100 logo">
				<a href="<?php echo home_url() ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ) ?> - <?php echo esc_attr( get_bloginfo( 'description', 'display' ) ) ?>" rel="home"><?php bloginfo( 'name' ) ?></a>
			</div>
			<div class="grid_9 grid-75 mobile-grid-100 nav">
				<?php ct_primary_nav_menu() ?>
			</div>
		</div>
<?php if ( is_front_page() && $visibility != 'off' ) { get_template_part('slider'); } ?>
